
package in.tekleads.services.bookservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import in.tekleads.entities.book.BookRequestType;
import in.tekleads.entities.book.BookResponseType;
import in.tekleads.entities.book.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IBookService", targetNamespace = "http://tekleads.in/services/BookService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IBookService {


    /**
     * 
     * @param parameters
     * @return
     *     returns in.tekleads.entities.book.BookResponseType
     */
    @WebMethod
    @WebResult(name = "BookResponseType", targetNamespace = "http://tekleads.in/entities/Book", partName = "parameters")
    public BookResponseType getBookByISDNRequestNumber(
        @WebParam(name = "BookRequestType", targetNamespace = "http://tekleads.in/entities/Book", partName = "parameters")
        BookRequestType parameters);

}
